config/routes.rb
Depot::Application.routes.draw do
  get "admin" => "admin#index"
  
  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end
  
  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, :on => :member
  end

  root :to => 'store#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "depot", :media => "all" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body id="store">
	<div id="banner">
		<%= image_tag("logo.png") %>
		<%= @page_title || "Pragmatic Bookshelf" %>
	</div>
	
	<div id="columns">
		<div id="side">
			<%= link_to 'Home', store_url %><br />
			<a href="./faq">Questions</a><br />
			<a href="./news">News</a><br />
			<a href="./contact">Contact</a>
			
			<p>
				<%= Time.now.strftime("Current Date: %m/%d/%Y") %><br />
				<%= Time.now.strftime("Current Time: %I:%M %P") %>
			</p>
			
			<% if session[:user_id] %>
				<br />
				<%= link_to "Orders", orders_path %><br />
				<%= link_to "Products", products_path %><br />
				<%= link_to "Users", users_path %><br /><br />
				<%= button_to "Logout", logout_path, :method => :delete %>
			<% end %>
			
			<% if @cart %>
				<%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %> 
					<%= render @cart %> 
				<% end %>
			<% end %>
		</div>
		<div id="main">
			<%= yield %>
		</div>
	</div>
</body>
</html>